### ISSUE TITLE
failed to run custom build command for `openssl-sys v0.9.74`

### ISSUE THREAD

**Issue by Z1W3** [alexcrichton/openssl-src-rs#149]

**Comment by Z1W3** [comment]
Compiling openssl v0.10.41
   Compiling openssl-sys v0.9.75
error: failed to run custom build command for `openssl-sys v0.9.75`

Caused by:
  process didn't exit successfully: `/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/debug/build/openssl-sys-142d7fbe1da909f9/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=WASM32_WASI_OPENSSL_NO_VENDOR
  WASM32_WASI_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  CC_wasm32-wasi = None
  CC_wasm32_wasi = None
  TARGET_CC = None
  CC = None
  CFLAGS_wasm32-wasi = None
  CFLAGS_wasm32_wasi = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  running "perl" "./Configure" "--prefix=/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/wasm32-wasi/debug/build/openssl-sys-a7bd188ca3d6e119/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "gcc" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=wasm32-wasi"
  Configuring OpenSSL version 1.1.1q (0x1010111fL) for gcc
  Using os-specific seed configuration
  Creating configdata.pm
  Creating Makefile

  The library could not be configured for supporting multi-threaded
  applications as the compiler options required on this system are not known.
  See file INSTALL for details if you need multi-threading.

  **********************************************************************
  ***                                                                ***
  ***   OpenSSL has been successfully configured                     ***
  ***                                                                ***
  ***   If you encounter a problem while building, please open an    ***
  ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
  ***   and include the output from the following command:           ***
  ***                                                                ***
  ***       perl configdata.pm --dump                                ***
  ***                                                                ***
  ***   (If you are new to OpenSSL, you might want to consult the    ***
  ***   'Troubleshooting' section in the INSTALL file first)         ***
  ***                                                                ***
  **********************************************************************
  running "make" "depend"
  running "make" "build_libs"
  perl "-I." -Mconfigdata "util/dofile.pl" \
            "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
  perl "-I." -Mconfigdata "util/dofile.pl" \
            "-oMakefile" include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
  perl "-I." -Mconfigdata "util/dofile.pl" \
            "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
  /Applications/Xcode.app/Contents/Developer/usr/bin/make depend && /Applications/Xcode.app/Contents/Developer/usr/bin/make _build_libs
  clang  -I. -Iinclude  -O3 -O2 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=wasm32-wasi -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/wasm32-wasi/debug/build/openssl-sys-a7bd188ca3d6e119/out/openssl-build/install/lib/engines-1.1\"" -DNDEBUG -I/usr/local/opt/openssl@3/include -MMD -MF apps/app_rand.d.tmp -MT apps/app_rand.o -c -o apps/app_rand.o apps/app_rand.c
  clang  -I. -Iinclude  -O3 -O2 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=wasm32-wasi -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/wasm32-wasi/debug/build/openssl-sys-a7bd188ca3d6e119/out/openssl-build/install/lib/engines-1.1\"" -DNDEBUG -I/usr/local/opt/openssl@3/include -MMD -MF apps/apps.d.tmp -MT apps/apps.o -c -o apps/apps.o apps/apps.c
  clang  -I. -Iinclude  -O3 -O2 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=wasm32-wasi -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/wasm32-wasi/debug/build/openssl-sys-a7bd188ca3d6e119/out/openssl-build/install/lib/engines-1.1\"" -DNDEBUG -I/usr/local/opt/openssl@3/include -MMD -MF apps/bf_prefix.d.tmp -MT apps/bf_prefix.o -c -o apps/bf_prefix.o apps/bf_prefix.c
  clang  -I. -Iinclude  -O3 -O2 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=wasm32-wasi -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/wasm32-wasi/debug/build/openssl-sys-a7bd188ca3d6e119/out/openssl-build/install/lib/engines-1.1\"" -DNDEBUG -I/usr/local/opt/openssl@3/include -MMD -MF apps/opt.d.tmp -MT apps/opt.o -c -o apps/opt.o apps/opt.c
  clang  -I. -Iinclude  -O3 -O2 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=wasm32-wasi -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/wasm32-wasi/debug/build/openssl-sys-a7bd188ca3d6e119/out/openssl-build/install/lib/engines-1.1\"" -DNDEBUG -I/usr/local/opt/openssl@3/include -MMD -MF apps/s_cb.d.tmp -MT apps/s_cb.o -c -o apps/s_cb.o apps/s_cb.c
  clang  -I. -Iinclude  -O3 -O2 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=wasm32-wasi -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/wasm32-wasi/debug/build/openssl-sys-a7bd188ca3d6e119/out/openssl-build/install/lib/engines-1.1\"" -DNDEBUG -I/usr/local/opt/openssl@3/include -MMD -MF apps/s_socket.d.tmp -MT apps/s_socket.o -c -o apps/s_socket.o apps/s_socket.c
  clang  -I. -Iinclude  -O3 -O2 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=wasm32-wasi -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/wasm32-wasi/debug/build/openssl-sys-a7bd188ca3d6e119/out/openssl-build/install/lib/engines-1.1\"" -DNDEBUG -I/usr/local/opt/openssl@3/include -MMD -MF crypto/aes/aes_cbc.d.tmp -MT crypto/aes/aes_cbc.o -c -o crypto/aes/aes_cbc.o crypto/aes/aes_cbc.c
  clang  -I. -Iinclude  -O3 -O2 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=wasm32-wasi -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/wasm32-wasi/debug/build/openssl-sys-a7bd188ca3d6e119/out/openssl-build/install/lib/engines-1.1\"" -DNDEBUG -I/usr/local/opt/openssl@3/include -MMD -MF crypto/aes/aes_cfb.d.tmp -MT crypto/aes/aes_cfb.o -c -o crypto/aes/aes_cfb.o crypto/aes/aes_cfb.c
  clang  -I. -Iinclude  -O3 -O2 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=wasm32-wasi -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/wasm32-wasi/debug/build/openssl-sys-a7bd188ca3d6e119/out/openssl-build/install/lib/engines-1.1\"" -DNDEBUG -I/usr/local/opt/openssl@3/include -MMD -MF crypto/aes/aes_core.d.tmp -MT crypto/aes/aes_core.o -c -o crypto/aes/aes_core.o crypto/aes/aes_core.c
  clang  -I. -Iinclude  -O3 -O2 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=wasm32-wasi -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/wasm32-wasi/debug/build/openssl-sys-a7bd188ca3d6e119/out/openssl-build/install/lib/engines-1.1\"" -DNDEBUG -I/usr/local/opt/openssl@3/include -MMD -MF crypto/aes/aes_ecb.d.tmp -MT crypto/aes/aes_ecb.o -c -o crypto/aes/aes_ecb.o crypto/aes/aes_ecb.c
  clang  -I. -Iinclude  -O3 -O2 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=wasm32-wasi -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/wasm32-wasi/debug/build/openssl-sys-a7bd188ca3d6e119/out/openssl-build/install/lib/engines-1.1\"" -DNDEBUG -I/usr/local/opt/openssl@3/include -MMD -MF crypto/aes/aes_ige.d.tmp -MT crypto/aes/aes_ige.o -c -o crypto/aes/aes_ige.o crypto/aes/aes_ige.c
  clang  -I. -Iinclude  -O3 -O2 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=wasm32-wasi -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/wasm32-wasi/debug/build/openssl-sys-a7bd188ca3d6e119/out/openssl-build/install/lib/engines-1.1\"" -DNDEBUG -I/usr/local/opt/openssl@3/include -MMD -MF crypto/aes/aes_misc.d.tmp -MT crypto/aes/aes_misc.o -c -o crypto/aes/aes_misc.o crypto/aes/aes_misc.c
  clang  -I. -Iinclude  -O3 -O2 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=wasm32-wasi -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/wasm32-wasi/debug/build/openssl-sys-a7bd188ca3d6e119/out/openssl-build/install/lib/engines-1.1\"" -DNDEBUG -I/usr/local/opt/openssl@3/include -MMD -MF crypto/aes/aes_ofb.d.tmp -MT crypto/aes/aes_ofb.o -c -o crypto/aes/aes_ofb.o crypto/aes/aes_ofb.c
  clang  -I. -Iinclude  -O3 -O2 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=wasm32-wasi -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/wasm32-wasi/debug/build/openssl-sys-a7bd188ca3d6e119/out/openssl-build/install/lib/engines-1.1\"" -DNDEBUG -I/usr/local/opt/openssl@3/include -MMD -MF crypto/aes/aes_wrap.d.tmp -MT crypto/aes/aes_wrap.o -c -o crypto/aes/aes_wrap.o crypto/aes/aes_wrap.c
  clang  -I. -Iinclude  -O3 -O2 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=wasm32-wasi -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/wasm32-wasi/debug/build/openssl-sys-a7bd188ca3d6e119/out/openssl-build/install/lib/engines-1.1\"" -DNDEBUG -I/usr/local/opt/openssl@3/include -MMD -MF crypto/aria/aria.d.tmp -MT crypto/aria/aria.o -c -o crypto/aria/aria.o crypto/aria/aria.c
  clang  -I. -Iinclude  -O3 -O2 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer --target=wasm32-wasi -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/Users/catt.zhi/Projects/AndroidStudioProjects/payease/fork_projects/ehking-common-android/hello-wasm4/target/wasm32-wasi/debug/build/openssl-sys-a7bd188ca3d6e119/out/openssl-build/install/lib/engines-1.1\"" -DNDEBUG -I/usr/local/opt/openssl@3/include -MMD -MF crypto/asn1/a_bitstr.d.tmp -MT crypto/asn1/a_bitstr.o -c -o crypto/asn1/a_bitstr.o crypto/asn1/a_bitstr.c

  --- stderr
  apps/s_cb.c:11:10: fatal error: 'stdio.h' file not found
  #include <stdio.h>
           ^~~~~~~~~
  apps/s_socket.c:11:10: fatal error: 'stdio.h' file not found
  #include <stdio.h>
           ^~~~~~~~~
  crypto/aes/aes_ecb.c:10:10: fatal error: 'assert.h' file not found
  In file included from apps/app_rand.c:10:
  In file included from #include <assert.h>
           ^~~~~~~~~~
  apps/apps.h:13:
  In file included from ./e_os.h:16:
  In file included from include/openssl/e_os2.h:243:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include/inttypes.h:21:15: fatal error: 'inttypes.h' file not found
  #include_next <inttypes.h>
                ^~~~~~~~~~~~
  In file included from apps/opt.c:9:
  In file included from apps/apps.h:13:
  In file included from ./e_os.h:16:
  In file included from include/openssl/e_os2.h:243:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include/inttypes.h:21:15: fatal error: 'inttypes.h' file not found
  crypto/aes/aes_core.c:39:10: fatal error: 'assert.h' file not found
  #include_next <inttypes.h>
                ^~~~~~~~~~~~
  #include <assert.h>
           ^~~~~~~~~~
  In file included from crypto/aria/aria.c:21:
  In file included from include/openssl/e_os2.h:243:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include/inttypes.h:21:15: fatal error: 'inttypes.h' file not found
  #include_next <inttypes.h>
                ^~~~~~~~~~~~
  In file included from crypto/aes/aes_misc.c:12:
  In file included from crypto/aes/aes_local.h:13:
  In file included from include/openssl/e_os2.h:243:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include/inttypes.h:21:15: fatal error: 'inttypes.h' file not found
  #include_next <inttypes.h>
                ^~~~~~~~~~~~
  In file included from crypto/aes/aes_ige.c:10In file included from crypto/aes/aes_wrap.c:10:
  include/internal/cryptlib.h:13:11: fatal error: 'stdlib.h' file not found
  :
  # include <stdlib.h>
            ^~~~~~~~~~
  include/internal/cryptlib.h:13:11: fatal error: 'stdlib.h' file not found
  # include <stdlib.h>
            ^~~~~~~~~~
  1 error generated.
  1 error generated.
  error: unable to create target: 'No available targets are compatible with triple "wasm32-unknown-wasi"'
  error: unable to create target: 'No available targets are compatible with triple "wasm32-unknown-wasi"'
  1 error generated.
  1 error generated.
  error: unable to create target: 'No available targets are compatible with triple "wasm32-unknown-wasi"'
  1 error generated.
  crypto/asn1/a_bitstr.c:11:10: fatal error: 'stdio.h' file not found
  #include <stdio.h>
           ^~~~~~~~~
  1 error generated.
  make[1]: *** [crypto/aes/aes_ofb.o] Error 1
  make[1]: *** Waiting for unfinished jobs....
  make[1]: *** [crypto/aes/aes_misc.o] Error 1
  make[1]: *** [crypto/aes/aes_ecb.o] Error 1
  make[1]: *** [crypto/aes/aes_cbc.o] Error 1
  apps/apps.c:18:10: fatal error: 'stdio.h' file not found
  #include <stdio.h>
           ^~~~~~~~~
  apps/bf_prefix.c:10:10: fatal error: 'stdio.h' file not found
  #include <stdio.h>
           ^~~~~~~~~
  make[1]: *** [crypto/aes/aes_cfb.o] Error 1
  make[1]: *** [crypto/aria/aria.o] Error 1
  1 error generated.
  make[1]: *** [crypto/aes/aes_core.o] Error 1
  1 error generated.
  make[1]: *** [crypto/aes/aes_wrap.o] Error 1
  1 error generated.
  make[1]: *** [crypto/aes/aes_ige.o] Error 1
  1 error generated.
  make[1]: *** [crypto/asn1/a_bitstr.o] Error 1
  1 error generated.
  1 error generated.
  make[1]: *** [apps/bf_prefix.o] Error 1
  make[1]: *** [apps/app_rand.o] Error 1
  1 error generated.
  make[1]: *** [apps/opt.o] Error 1
  1 error generated.
  make[1]: *** [apps/s_socket.o] Error 1
  1 error generated.
  make[1]: *** [apps/s_cb.o] Error 1
  1 error generated.
  make[1]: *** [apps/apps.o] Error 1
  make: *** [build_libs] Error 2
  thread 'main' panicked at '


  Error building OpenSSL:
      Command: "make" "build_libs"
      Exit status: exit status: 2


      ', /Users/catt.zhi/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.22.0+1.1.1q/src/lib.rs:490:13
  stack backtrace:
     0:        0x1080221b4 - std::backtrace_rs::backtrace::libunwind::trace::hee82a97921985ffc
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:        0x1080221b4 - std::backtrace_rs::backtrace::trace_unsynchronized::hd2f3f197f68d4196
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x1080221b4 - std::sys_common::backtrace::_print_fmt::hef7f7070435a43cf
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:66:5
     3:        0x1080221b4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6ab6a4b798848da1
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:45:22
     4:        0x10803caab - core::fmt::write::h3cfeb2e4a41b5943
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/fmt/mod.rs:1196:17
     5:        0x10801ea88 - std::io::Write::write_fmt::h207c490a0e714424
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/io/mod.rs:1654:15
     6:        0x10802444d - std::sys_common::backtrace::_print::h2c39637d8acc9668
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:48:5
     7:        0x10802444d - std::sys_common::backtrace::print::ha24f17eeb0536253
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:35:9
     8:        0x10802444d - std::panicking::default_hook::{{closure}}::h2dad0ca14a5f6fb3
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:295:22
     9:        0x108024131 - std::panicking::default_hook::he28ca1b524a71648
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:314:9
    10:        0x1080249ce - std::panicking::rust_panic_with_hook::hc50fd680dab3e13f
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:698:17
    11:        0x1080248c3 - std::panicking::begin_panic_handler::{{closure}}::h73da24fc37eba97b
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:588:13
    12:        0x108022637 - std::sys_common::backtrace::__rust_end_short_backtrace::hff104f8fa804dc90
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:138:18
    13:        0x10802459a - rust_begin_unwind
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
    14:        0x108046183 - core::panicking::panic_fmt::hf5e95a7953f70bca
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
    15:        0x107f8c136 - openssl_src::Build::run_command::h268145f1e5811d0c
                                 at /Users/catt.zhi/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.22.0+1.1.1q/src/lib.rs:490:13
    16:        0x107f8b7dc - openssl_src::Build::build::h0cde65246d9ab6d8
                                 at /Users/catt.zhi/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.22.0+1.1.1q/src/lib.rs:462:13
    17:        0x107f53890 - build_script_main::find_vendored::get_openssl::h51badb27526fc928
                                 at /Users/catt.zhi/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.75/build/find_vendored.rs:5:21
    18:        0x107f4d623 - build_script_main::find_openssl::h048ea80572f97a77
                                 at /Users/catt.zhi/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.75/build/main.rs:57:20
    19:        0x107f4d72f - build_script_main::main::hab857904629abe2d
                                 at /Users/catt.zhi/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.75/build/main.rs:68:35
    20:        0x107f5317e - core::ops::function::FnOnce::call_once::h0ef58b45c9ce9379
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
    21:        0x107f54071 - std::sys_common::backtrace::__rust_begin_short_backtrace::h86efd40681ca690d
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:122:18
    22:        0x107f59494 - std::rt::lang_start::{{closure}}::h81d0f76ee4b55581
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:145:18
    23:        0x108019a7e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h95efaa71c50a181d
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:280:13
    24:        0x108019a7e - std::panicking::try::do_call::h9e262f45d279a668
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
    25:        0x108019a7e - std::panicking::try::hcfa2ff7c3ef05946
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
    26:        0x108019a7e - std::panic::catch_unwind::h6e5f05af2d5ed125
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
    27:        0x108019a7e - std::rt::lang_start_internal::{{closure}}::ha6428ebd453bcc4b
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:48
    28:        0x108019a7e - std::panicking::try::do_call::h1897e56454854402
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
    29:        0x108019a7e - std::panicking::try::h18317894fcdd1ee4
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
    30:        0x108019a7e - std::panic::catch_unwind::h953eb8e106926f6b
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
    31:        0x108019a7e - std::rt::lang_start_internal::h3a2ed64a839cce39
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:20
    32:        0x107f5946e - std::rt::lang_start::hfd8ea766d5846684
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:144:17
    33:        0x107f51156 - _main

**Comment by souravs17031999** [comment]
@Z1W3 were you able to build it ? I am facing same problem
